In [2]:
import tensorflow as tf

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [13]:
sent = {
    "I‘m happy.",
    "She exercises every morning.",
    "His dog barks loudly.",
    "My school starts at 8:00.",
    "We always eat dinner together.",
    "They take the bus to work.",
    "He doesn’t like vegetables.",
    "I don’t want anything to drink.",
    "This little black dress isn’t expensive. ",
    "Those kids don’t speak English."
}
#unqual size
voc_size = 10000
oh = [one_hot(s,voc_size) for s in sent]

In [14]:
oh

[[1608, 1627, 9029, 2117, 9668, 6715],
 [9631, 7943],
 [9156, 646, 6432, 3002, 9668, 5222],
 [6820, 2586, 7893, 4932, 3829, 7452],
 [4187, 2505, 646, 1226, 1460],
 [7767, 9041, 5333, 5164],
 [7267, 8161, 5469, 3690],
 [3577, 800, 493, 6007],
 [6597, 5230, 6872, 219, 460],
 [5492, 4286, 6292, 2232, 1410, 9515]]

In [15]:
#word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np
import pandas as pd

In [16]:
sent_len=6
embedded_docs=pad_sequences(oh,padding='pre',maxlen=sent_len)

In [17]:
embedded_docs

array([[1608, 1627, 9029, 2117, 9668, 6715],
       [   0,    0,    0,    0, 9631, 7943],
       [9156,  646, 6432, 3002, 9668, 5222],
       [6820, 2586, 7893, 4932, 3829, 7452],
       [   0, 4187, 2505,  646, 1226, 1460],
       [   0,    0, 7767, 9041, 5333, 5164],
       [   0,    0, 7267, 8161, 5469, 3690],
       [   0,    0, 3577,  800,  493, 6007],
       [   0, 6597, 5230, 6872,  219,  460],
       [5492, 4286, 6292, 2232, 1410, 9515]])

In [19]:
dim = 6

model =Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

c:\Users\rashm\Downloads\NLP_KN\RNNproject\newenv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [23]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step


array([[[-0.0321958 , -0.00186715, -0.02024927,  0.00237636,
         -0.03047769,  0.0103577 ],
        [ 0.00656663,  0.04166285, -0.03693184, -0.04721631,
         -0.00482533,  0.01912085],
        [-0.03220236, -0.04948257, -0.0463444 , -0.00333669,
          0.01928562,  0.04171497],
        [-0.0174351 , -0.01616772,  0.04604821, -0.03124458,
         -0.03246965,  0.04451622],
        [ 0.0135585 , -0.0048502 ,  0.02287899, -0.04395734,
         -0.0040037 ,  0.01221496],
        [-0.01678742, -0.04417207, -0.03908096, -0.04163005,
         -0.04292727,  0.02399002]],

       [[-0.02583604, -0.04280755, -0.02470218, -0.00406779,
          0.0406982 ,  0.03222903],
        [-0.02583604, -0.04280755, -0.02470218, -0.00406779,
          0.0406982 ,  0.03222903],
        [-0.02583604, -0.04280755, -0.02470218, -0.00406779,
          0.0406982 ,  0.03222903],
        [-0.02583604, -0.04280755, -0.02470218, -0.00406779,
          0.0406982 ,  0.03222903],
        [ 0.00501835,  0.009

In [21]:
embedded_docs[0]

array([1608, 1627, 9029, 2117, 9668, 6715])